apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: loki  # ⬅️ Necessário para cross-link com Tempo
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'  # ⬅️ Bate com o uid acima
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: ['service.name', 'service_name', 'job', 'instance']  # ⬅️ Adicione 'service.name' e 'service_name'
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: 'prometheus'
