receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
      - name: http.method
      - name: http.status_code

  resource:
    attributes:
      - action: upsert
        key: service.name
        value: observabilidade-app

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlp:
    endpoint: tempo:9095
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: single-tenant

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch, spanmetrics]
      exporters: [otlp]

    metrics:
      receivers: [otlp]  # <- Corrigido aqui
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
